// src/components/AboutHeader.vue
<template>
  <div :class="$style.wrap">
    <a :class="$style.link" href="https://github.com/chaosdorf/dorfmap"
      >dorfmap</a
    >
    |
    <a :class="$style.link" href="https://wiki.chaosdorf.de/Lichtsteuerung"
      >about</a
    >
    |
    <a :class="$style.link" href="https://wiki.chaosdorf.de/Lichtsteuerung#API"
      >API</a
    >
    |
    <a :class="$style.link" href="/space_api.json">spaceApi</a>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class AboutHeader extends Vue {}
</script>

<style module>
.wrap {
  position: fixed;
  top: 5px;
  right: 15px;
  font-family: monospace;
  font-size: smaller;
}
.link {
  color: #006;
  text-decoration: none;
  margin: 5px;
}
</style>

// src/Components/AboutHeader.tsx
import React from 'react';
import useStyles from './AboutHeader.style';

const AboutHeader = () => {
  const classes = useStyles();

  return (
    <div className={classes.main}>
      <a className={classes.link} href="https://github.com/chaosdorf/dorfmap">
        {'dorfmap'}
      </a>{' '}
      {'|'}{' '}
      <a
        className={classes.link}
        href="https://wiki.chaosdorf.de/Lichtsteuerung"
      >
        {'about'}
      </a>{' '}
      {'|'}{' '}
      <a
        className={classes.link}
        href="https://wiki.chaosdorf.de/Lichtsteuerung#API"
      >
        {'API'}
      </a>{' '}
      {'|'}{' '}
      <a className={classes.link} href="/space_api.json">
        {'spaceAPI'}
      </a>
    </div>
  );
};

export default AboutHeader;
