// src/Components/Lamp.tsx
import './Lamp.scss';
import { AppState } from 'AppState';
import { connect } from 'react-redux';
import { toggleDevice } from 'actions/device';
import BlinkenlightPopup from './BlinkenlightPopup';
import cc from 'classnames';
import React, { ReactNode } from 'react';
import Tooltip from '@material-ui/core/Tooltip';

const TooltipImg = ({ tooltip, ...props }: any) => (
  <Tooltip placement="top" title={tooltip}>
    <img {...props} />
  </Tooltip>
);

export type Lamp = {
  status_text?: string,
  rate_delay: number,
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  name: string,
  type: string,
  status: 0 | 1,
  duplicates?: Lamp[],
  layer: string,
  image: string,
  is_writable: number,
};

type DispatchProps = {
  toggleDevice: typeof toggleDevice,
};
type OwnProps = {
  lamp: Lamp,
};
type Props = DispatchProps & OwnProps;

type State = {
  dialogOpen: boolean,
};

class LampComponent extends React.Component<Props, State> {
  static style = {
    lamp: {
      writeable: {
        cursor: 'pointer',
        transition: '300ms linear',
        ':hover': {
          transform: 'scale(1.3)',
        },
      },
      normal: {
        position: 'absolute',
      },
    },
  };
  state: State = {
    dialogOpen: false,
  };
  getTooltipText(lamp: Lamp) {
    let text = lamp.status_text;

    if (!text) {
      return null;
    }
    if (lamp.rate_delay > 0) {
      text = `${text} (${lamp.rate_delay}s)`;
    }
    /* eslint-disable react/no-danger */

    return <div dangerouslySetInnerHTML={{ __html: text }} />;

    /* eslint-enable react/no-danger */
  }
  getDuplicate(lamp: Lamp, tooltipText?: ReactNode) {
    if (!lamp.duplicates || !lamp.duplicates.length) {
      return null;
    }

    const dup = lamp.duplicates[0];
    const dupStyle = {
      left: dup.x1,
      top: dup.y1,
      width: lamp.x2,
      height: lamp.y2,
    };

    const cssClass = cc(['Lamp', { 'Lamp--writeable': lamp.is_writable && lamp.rate_delay <= 0 }]);
    const imgProps = {
      className: cssClass,
      onClick: this.toggle,
      name: lamp.name,
      style: dupStyle,
      src: lamp.image,
    };

    if (tooltipText) {
      return <TooltipImg {...imgProps} tooltip={tooltipText} />;
    }

    return <img {...imgProps} />;
  }
  toggle = () => {
    const { lamp, toggleDevice } = this.props;

    if (!lamp.is_writable) {
      return;
    }
    if (lamp.type === 'charwrite' || lamp.type === 'blinkenlight') {
      // if (lamp.type === 'charwrite' || lamp.type === 'blinkenlight' || lamp.type === 'beamer') {
      this.setState({
        dialogOpen: true,
      });
    } else if (lamp.rate_delay <= 0) {
      toggleDevice(lamp);
    }
  };
  handleRequestClose = () => {
    this.setState({
      dialogOpen: false,
    });
  };
  componentDidMount() {
    this.delayCheck(this.props);
  }
  UNSAFE_componentWillReceiveProps(props: Props) {
    this.delayCheck(props);
  }
  doesReduce: boolean = false;
  delayCheck = (props: Props) => {
    const { lamp } = props;

    if (lamp.rate_delay > 0 && !this.doesReduce) {
      this.reduceDelay();
    }
  };
  reduceDelay() {
    this.doesReduce = true;
    setTimeout(() => {
      const { lamp } = this.props;

      this.doesReduce = false;
      lamp.rate_delay -= 1;
      this.forceUpdate();
      if (lamp.rate_delay > 0) {
        this.reduceDelay();
      }
    }, 1000);
  }
  render() {
    const { lamp } = this.props;
    const { dialogOpen } = this.state;
    const style = {
      left: lamp.x1,
      top: lamp.y1,
      width: lamp.x2,
      height: lamp.y2,
    };
    const cssClass = cc(['Lamp', { 'Lamp--writeable': lamp.is_writable && lamp.rate_delay <= 0 }]);

    const tooltipText = this.getTooltipText(lamp);
    const imgProps = {
      className: cssClass,
      onClick: this.toggle,
      name: lamp.name,
      style,
      src: lamp.image,
    };
    let image;

    if (tooltipText) {
      image = <TooltipImg {...imgProps} tooltip={tooltipText} />;
    } else {
      image = <img {...imgProps} />;
    }

    let dialog;

    if (lamp.type === 'blinkenlight') {
      dialog = dialogOpen && <BlinkenlightPopup onRequestClose={this.handleRequestClose} lamp={lamp} />;
    }

    return (
      <>
        {image}
        {this.getDuplicate(lamp, tooltipText)}
        {dialog}
      </>
    );
  }
}

export default connect<{}, DispatchProps, OwnProps, AppState>(
  undefined,
  {
    toggleDevice,
  }
)(LampComponent);

// src/components/Lamp.vue
<template>
  <div>
    <b-tooltip
      position="is-right"
      v-for="(lampC, i) in lamps"
      :key="i"
      :label="tooltipText"
      :style="{
        left: `${lampC.x1}px`,
        top: `${lampC.y1}px`,
        width: `${lampC.x2}px`,
        height: `${lampC.y2}px`,
      }"
      class="lamp"
    >
      <img
        @click="toggle"
        :class="{ writeable: writeable }"
        :src="lamp.image"
      />
    </b-tooltip>
    <b-modal
      v-if="isBlinkenlight"
      :active.sync="blinkenlightOpen"
      has-modal-card
    >
      <BlinkenlightPopup :lamp="lamp" />
    </b-modal>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { Lamp as LampType } from '@/store/Devices';
import Devices from '@/store/Devices';
import { getModule } from 'vuex-module-decorators';
import he from 'he';
import BlinkenlightPopup from './BlinkenlightPopup.vue';

@Component({
  components: {
    BlinkenlightPopup,
  },
})
export default class Lamp extends Vue {
  @Prop() readonly lamp!: LampType;
  devicesStore = getModule(Devices);
  blinkenlightOpen = false;
  get isBlinkenlight() {
    return this.lamp.type === 'blinkenlight';
  }
  toggle() {
    switch (this.lamp.type) {
      case 'blinkenlight':
        this.blinkenlightOpen = !this.blinkenlightOpen;
        break;
      default:
        if (this.writeable) {
          this.devicesStore.toggleDevice(this.lamp.name);
        }
        break;
    }
  }
  tooltipText: string = '';
  reducingDelay: boolean = false;
  get lamps() {
    return [...(this.lamp.duplicates || []), this.lamp];
  }
  beforeUpdate() {
    this.initDelayCheck();
  }
  initDelayCheck() {
    if (!this.reducingDelay) {
      this.checkDelay();
    }
  }
  get writeable() {
    return (
      this.lamp.is_writable &&
      (this.lamp.rate_delay <= 0 || this.lamp.status === 1)
    );
  }
  checkDelay() {
    let baseText = `${he
      .unescape(this.lamp.status_text || '')
      .replace('<br/>', '  ')}`;
    if (this.lamp.rate_delay > 0 && this.lamp.status === 0) {
      this.reducingDelay = true;
      baseText += ` (${this.lamp.rate_delay}s)`;
      setTimeout(() => {
        this.lamp.rate_delay -= 1;
        this.$forceUpdate();
        this.checkDelay();
      }, 1000);
    } else {
      this.reducingDelay = false;
    }
    this.tooltipText = baseText;
  }
  mounted() {
    this.initDelayCheck();
  }
}
</script>

<style lang="scss" scoped>
.lamp {
  position: absolute;
}
.writeable {
  cursor: pointer;
  transition: 300ms linear;
  &:hover {
    transform: scale(1.3);
  }
}
.modal-card {
  width: auto;
}
</style>
