// src/components/Lamp.vue
<template>
  <div>
    <b-tooltip
      position="is-right"
      v-for="(lampC, i) in lamps"
      :key="i"
      :label="tooltipText"
      :style="{
        left: `${lampC.x1}px`,
        top: `${lampC.y1}px`,
        width: `${lampC.x2}px`,
        height: `${lampC.y2}px`,
      }"
      class="lamp"
    >
      <img
        @click="toggle"
        :class="{ writeable: writeable }"
        :src="lamp.image"
      />
    </b-tooltip>
    <b-modal
      v-if="isBlinkenlight"
      :active.sync="blinkenlightOpen"
      has-modal-card
    >
      <BlinkenlightPopup :lamp="lamp" />
    </b-modal>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { Lamp as LampType } from '@/store/Devices';
import Devices from '@/store/Devices';
import { getModule } from 'vuex-module-decorators';
import he from 'he';
import BlinkenlightPopup from './BlinkenlightPopup.vue';

@Component({
  components: {
    BlinkenlightPopup,
  },
})
export default class Lamp extends Vue {
  @Prop() readonly lamp!: LampType;
  devicesStore = getModule(Devices);
  blinkenlightOpen = false;
  get isBlinkenlight() {
    return this.lamp.type === 'blinkenlight';
  }
  toggle() {
    switch (this.lamp.type) {
      case 'blinkenlight':
        this.blinkenlightOpen = !this.blinkenlightOpen;
        break;
      default:
        if (this.writeable) {
          this.devicesStore.toggleDevice(this.lamp.name);
        }
        break;
    }
  }
  tooltipText: string = '';
  reducingDelay: boolean = false;
  get lamps() {
    return [...(this.lamp.duplicates || []), this.lamp];
  }
  beforeUpdate() {
    this.initDelayCheck();
  }
  initDelayCheck() {
    if (!this.reducingDelay) {
      this.checkDelay();
    }
  }
  get writeable() {
    return (
      this.lamp.is_writable &&
      (this.lamp.rate_delay <= 0 || this.lamp.status === 1)
    );
  }
  checkDelay() {
    let baseText = `${he
      .unescape(this.lamp.status_text || '')
      .replace('<br/>', '  ')}`;
    if (this.lamp.rate_delay > 0 && this.lamp.status === 0) {
      this.reducingDelay = true;
      baseText += ` (${this.lamp.rate_delay}s)`;
      setTimeout(() => {
        this.lamp.rate_delay -= 1;
        this.$forceUpdate();
        this.checkDelay();
      }, 1000);
    } else {
      this.reducingDelay = false;
    }
    this.tooltipText = baseText;
  }
  mounted() {
    this.initDelayCheck();
  }
}
</script>

<style lang="scss" scoped>
.lamp {
  position: absolute;
}
.writeable {
  cursor: pointer;
  transition: 300ms linear;
  &:hover {
    transform: scale(1.3);
  }
}
.modal-card {
  width: auto;
}
</style>

// src/Components/Lamp.jsx
/* @flow */
import { autobind } from 'core-decorators';
import { toggleDevice, reduceDelay } from '../Actions/devices';
import BlinkenlightPopup from './BlinkenlightPopup';
import ConfiguredRadium from 'configuredRadium';
import React from 'react';
import Tooltip from 'rc-tooltip';

function getImage(lamp: Object) {
  let status = '';
  switch (lamp.status) {
    case 0:
    case '0':
    status = '_off';
    break;
    case 1:
    case '1':
    status = '_on';
    break;
    default:
    break;
  }
  let baseImage;
  switch (lamp.type) {
    case 'light':
    baseImage = 'light';
    break;
    case 'light_au':
    if (lamp.auto) {
      baseImage = 'light_auto';
    } else {
      baseImage = 'light_noauto';
    }
    break;
    default:
    baseImage = lamp.type;
    break;
  }
  return `static/images/${baseImage}${status}.png`;
}

type Props = {
  lamp: Lamp,
}

type State = {
  dialogOpen: bool,
}

@ConfiguredRadium
export default class LampComponent extends React.Component {
  props: Props;
  static propTypes = {
    lamp: React.PropTypes.object.isRequired,
  };
  static style = {
    lamp: {
      writeable: {
        cursor: 'pointer',
        transition: '300ms linear',
        ':hover': {
          transform: 'scale(1.3)',
        },
      },
      normal: {
        position: 'absolute',
      },
    },
  };
  state: State = {
    dialogOpen: false,
  };
  getTooltipText(lamp: Lamp): ?React.Element<*> {
    let text = lamp.status_text;
    if (!text) {
      return null;
    }
    if (lamp.rate_delay > 0) {
      text = `${text} (${lamp.rate_delay}s)`;
    }
    /* eslint-disable react/no-danger */
    return <div dangerouslySetInnerHTML={{ __html: text }}/>;
    /* eslint-enable react/no-danger */
  }
  getDuplicate(lamp: Lamp, tooltipText: ?React.Element<*>) {
    if (!lamp.duplicates || !lamp.duplicates.length) {
      return null;
    }

    const dup = lamp.duplicates[0];
    const dupStyle = [LampComponent.style.lamp.normal, {
      left: dup.x1,
      top: dup.y1,
      width: lamp.x2,
      height: lamp.y2,
    }];
    if (lamp.is_writable && lamp.rate_delay <= 0) {
      dupStyle.push(LampComponent.style.lamp.writeable);
    }
    return (
      <Tooltip destroyTooltipOnHide
        overlay={tooltipText}>
        <img
          ref="duplicate"
          onClick={this.toggle}
          name={lamp.name}
          style={dupStyle}
          src={getImage(lamp)}/>
      </Tooltip>
    );
  }
  @autobind
  toggle() {
    const { lamp } = this.props;
    if (lamp.type === 'charwrite' || lamp.type === 'blinkenlight') {
      this.setState({
        dialogOpen: true,
      });
    } else if (lamp.rate_delay <= 0) {
      toggleDevice(lamp);
    }
  }
  @autobind
  handleRequestClose() {
    this.setState({
      dialogOpen: false,
    });
  }
  doesReduce: bool = false;
  componentWillReceiveProps(props: Props) {
    const { lamp } = props;
    if (lamp.status === 1) {
      /* eslint-disable camelcase */
      lamp.rate_delay = 0;
      this.doesReduce = false;
    } else if (lamp.rate_delay > 0 && !this.doesReduce) {
      this.reduceDelay(lamp);
      // reduceDelay(lamp);
    }
  }
  reduceDelay(lamp: Lamp) {
    this.doesReduce = true;
    setTimeout(() => {
      lamp.rate_delay -= 1;
      this.forceUpdate();
      if (lamp.rate_delay <= 0) {
        /* eslint-enable camelcase */
        reduceDelay(lamp, false);
      } else {
        this.reduceDelay(lamp);
      }
    }, 1000);
  }
  render() {
    const { lamp } = this.props;
    const { dialogOpen } = this.state;
    const style = [LampComponent.style.lamp.normal, {
      left: lamp.x1,
      top: lamp.y1,
      width: lamp.x2,
      height: lamp.y2,
    }];
    if (lamp.is_writable && lamp.rate_delay <= 0) {
      style.push(LampComponent.style.lamp.writeable);
    }
    let dialog;
    if (lamp.type === 'blinkenlight') {
      dialog = (<BlinkenlightPopup onRequestClose={this.handleRequestClose} open={dialogOpen} lamp={lamp}/>);
    }
    const tooltipText = this.getTooltipText(lamp);
    const img = (
      <img
        ref="normal"
        onClick={this.toggle}
        name={lamp.name}
        style={style}
        src={getImage(lamp)}/>
    );
    return (
      <div>
        {
          tooltipText ? (<Tooltip overlay={tooltipText}>
            {img}
          </Tooltip>) : img
        }
        {this.getDuplicate(lamp, tooltipText)}
        {dialog}
      </div>
    );
  }
}
